"""initial schema

Revision ID: 32a98e5118db
Revises: 
Create Date: 2026-06-06 08:22:42.557903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a98e5118db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('chave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'chave', name='uq_config_tenant_chave')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('estado_uf', sa.String(length=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colaboradores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('matricula', sa.String(length=40), nullable=False),
    sa.Column('setor', sa.String(length=80), nullable=False),
    sa.Column('funcao', sa.String(length=80), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('consentimento_dados', sa.Boolean(), nullable=True),
    sa.Column('data_consentimento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'matricula', name='uq_colab_tenant_matricula')
    )
    op.create_index('ix_colab_tenant_ativo', 'colaboradores', ['tenant_id', 'ativo'], unique=False)
    op.create_table('epis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('ca', sa.String(length=20), nullable=False),
    sa.Column('fabricante', sa.String(length=120), nullable=False),
    sa.Column('tipo_protecao', sa.String(length=60), nullable=False),
    sa.Column('vida_util_dias', sa.Integer(), nullable=True),
    sa.Column('validade_ca', sa.Date(), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('foto_path', sa.String(length=300), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_epis_tenant_ativo', 'epis', ['tenant_id', 'ativo'], unique=False)
    op.create_table('setores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nome', name='uq_setor_tenant_nome')
    )
    op.create_index(op.f('ix_setores_tenant_id'), 'setores', ['tenant_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('login', sa.String(length=60), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('precisa_trocar_senha', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_login'), 'usuarios', ['login'], unique=True)
    op.create_index(op.f('ix_usuarios_tenant_id'), 'usuarios', ['tenant_id'], unique=False)
    op.create_table('entregas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('colaborador_id', sa.String(), nullable=False),
    sa.Column('epi_id', sa.String(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('validade_prevista', sa.Date(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('responsavel', sa.String(length=120), nullable=True),
    sa.Column('pdf_path', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['epi_id'], ['epis.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entregas_tenant_data', 'entregas', ['tenant_id', 'data'], unique=False)
    op.create_table('movimentacoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('epi_id', sa.String(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=300), nullable=False),
    sa.Column('documento_nf', sa.String(length=80), nullable=True),
    sa.Column('responsavel', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['epi_id'], ['epis.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mov_epi', 'movimentacoes', ['epi_id'], unique=False)
    op.create_index('ix_mov_tenant_data', 'movimentacoes', ['tenant_id', 'data'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mov_tenant_data', table_name='movimentacoes')
    op.drop_index('ix_mov_epi', table_name='movimentacoes')
    op.drop_table('movimentacoes')
    op.drop_index('ix_entregas_tenant_data', table_name='entregas')
    op.drop_table('entregas')
    op.drop_index(op.f('ix_usuarios_tenant_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_login'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_setores_tenant_id'), table_name='setores')
    op.drop_table('setores')
    op.drop_index('ix_epis_tenant_ativo', table_name='epis')
    op.drop_table('epis')
    op.drop_index('ix_colab_tenant_ativo', table_name='colaboradores')
    op.drop_table('colaboradores')
    op.drop_table('tenants')
    op.drop_table('configs')
    # ### end Alembic commands ###
